# Generated by Django 3.0.3 on 2021-11-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='data',
            field=models.CharField(max_length=500000),
        ),
    ]
