# Generated by Django 3.0.3 on 2021-11-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetest', '0002_auto_20211108_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='data',
            field=models.TextField(),
        ),
    ]
