# Generated by Django 3.0.3 on 2021-11-19 19:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetest', '0003_auto_20211108_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8),
        ),
    ]
